from api.test.test_serializers.company import CompanySerializerTestCase
from api.test.test_serializers.cashback import CashbackSerializerTestCase
from api.test.test_serializers.sale import SaleSerializerTestCase